CREATE TABLE Users (
    UserId INTEGER NOT NULL PRIMARY KEY,
    FirstName VARCHAR(30) NOT NULL DEFAULT '',
    MiddleName VARCHAR(30) DEFAULT '',
    LastName VARCHAR(30) NOT NULL DEFAULT '',
    SSN VARCHAR(11) UNIQUE NOT NULL DEFAULT '',
    PhoneNumber VARCHAR(12) NOT NULL DEFAULT '',
    Address VARCHAR(30) NOT NULL DEFAULT '',
    Username VARCHAR(30) UNIQUE NOT NULL DEFAULT '',
    Password VARCHAR(30) NOT NULL DEFAULT '',
    Email VARCHAR(30) UNIQUE NOT NULL DEFAULT ''
);

CREATE TABLE Accounts (
    AccountId INTEGER NOT NULL PRIMARY KEY,
    UserId INTEGER NOT NULL DEFAULT '',
    ProfitLoss DOUBLE NOT NULL DEFAULT 0,
    PositionsHeld INTEGER NOT NULL DEFAULT 0,
    MarketValue DOUBLE NOT NULL DEFAULT 0,
    NetValue DOUBLE NOT NULL DEFAULT 0,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OwnedPositions (
    OwnedPositionId INTEGER NOT NULL PRIMARY KEY,
    AccountId INTEGER NOT NULL,
    StockSymbol VARCHAR(5) NOT NULL,
    OrderId INTEGER NOT NULL,
    Quantity INTEGER NOT NULL,
    InitialValue DOUBLE NOT NULL,
    MarketValue DOUBLE NOT NULL,
    ProfitLoss DOUBLE NOT NULL
);

CREATE TABLE Stocks (
    StockSymbol VARCHAR(5) NOT NULL,
    Name VARCHAR(30) NOT NULL,
    Description VARCHAR(60) NOT NULL,
    Sector VARCHAR(30) NOT NULL,
    CurrentPrice DOUBLE NOT NULL
);

CREATE TABLE Orders (
    OrderId INTEGER PRIMARY KEY,
    AccountId INTEGER NOT NULL,
    StockSymbol VARCHAR(5) NOT NULL,
    OrderBuyOrSell VARCHAR(4) NOT NULL, 
    OrderType VARCHAR(10) NOT NULL,
    Quantity INTEGER NOT NULL,
    Price DOUBLE NOT NULL,
    Status VARCHAR(15) NOT NULL
);